apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: spark-worker
  namespace: ssd-stack
  labels:
    app: spark-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spark-worker
  template:
    metadata:
      labels:
        app: spark-worker
    spec:
      containers:
      - name: spark-worker
        image: rafabsb/spark-k8s:spark-2.2.0-hadoop2.7.4
        imagePullPolicy: "IfNotPresent"
        env:
        - name: SPARK_TYPE
          value: worker
        ports:
        - containerPort: 8081
          name: worker-webui
        command: ["/bin/sh"]
        args: ["-c", "./run.sh ; sleep infinity"]
        resources:
           requests:
             memory: "256Mi"
             cpu: "100m"
           limits:
             memory: "1024Mi"
             cpu: "500m"