apiVersion: v1
kind: Service
metadata:
  name: hadoop-namenode
  namespace: ssd-stack
spec:
  ports:
  - name: webui
    port: 50070
    targetPort: 50070
  - name: hdfs
    port: 8020
    targetPort: 8020
  selector:
    app: hadoop-namenode